# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vQH1l3u-tZUZfsLIeDSubbLEXVOJ6uHf
"""

#1
def area_rectangle():
  l=int(input("Please enter the Length of the rectangle:"))
  w=int(input("Please enter the width of the rectangle: "))
  a=l*w
  return a

area_rectangle()

#2
def BMI():
  w=int(input("Please enter the Weight in Kgs: "))
  h=float(input("Please enter the height in meteres: "))
  b=w/h
  return b

BMI()

#3
dict_students={"Arpit":63,"Akash":40,"Ashu":79,"Akshansh":69}
print(dict_students.items())

#4
age=int(input("Please enter your age: "))
if age<18:
  print("Minor")
elif age>60:
  print("Senior Citizen")
else:
  print("Adult")

#5
for i in range(1,51):
  if i % 2 == 0:
    print(i)

#6
password=None
while password!='Arpit':
  password=input("Please enter the correct password:")
print("Youv've Entered the correct password welcome to the club")

#7
def avglist(clist):
  total_num=0
  total_sum=0
  for i in clist:
    total_num+=1
    total_sum+=i
  return total_sum/total_num

avglist([1,2,3,4])

#8
def count_vowels(abc):
  c=0
  for i in abc:
    if 'a'== i or 'e'== i or 'i'== i or 'o'== i or 'u'== i:
      c+=1
  return c

count_vowels('aeiou')

#9
from datetime import datetime
datetime.now()

#10
a=None
b=None
while type(a)!= int and type(b)!= int :
  try:
    a=int(input())
    b=int(input())
    c=a+b
  except:
    print("Please Enter the value in integer form :")
  finally:
    print("The Addition operation adds to numbers",c)

#11
c=int(input())
try:
  del d
except:
  print("Please Enter value of d first ")

finally:
  print("Operation Ended")

#12
a=4
b=0
try:
  c=a/b
except:
  print("You Cannot Divide a Number by 0 please Choose appropriate divisor")
finally:
  print("operation Closed")

#13
f=open("g.txt",'w')
f.write('Hello Python!')

#14
f=open("g.txt",'w')
f.write('Hello Python!')
f=open("g.txt",'r')
print(f.read())

#15
f=open("g.txt",'a')
f.write(' is Very grateful to have you ')
f=open("g.txt",'r')
print(f.read())

