# -*- coding: utf-8 -*-
"""lvadsusr71_arpit_lab4_anomaly.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F1V-vXMAM2MZ4nx6XnxCvtY9CVWXJA5f
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.ensemble import IsolationForest

data_social=pd.read_csv("/content/social_network.csv")

data_social.head(10)

data_social.info()

data_social.isnull(). sum()

social_network_data=data_social

plt.figure(figsize=(18, 5))
features = ['login_activity', 'posting_activity', 'social_connections']
for i, feature in enumerate(features, 1):
    plt.subplot(1, 3, i)
    sns.histplot(data=social_network_data, x=feature, kde=True)
    plt.title(f'{feature} Distribution')
plt.tight_layout()
plt.show()

X = social_network_data[features]

model = IsolationForest(n_estimators=100, contamination='auto', random_state=42)
predictions = model.fit_predict(X)

social_network_data['anomaly_score'] = model.decision_function(X)
social_network_data['is_anomaly'] = predictions
social_network_data['is_anomaly'] = social_network_data['is_anomaly'].apply(lambda x: 1 if x == -1 else 0)

print(social_network_data.head())
print(social_network_data['is_anomaly'].value_counts())

plt.figure(figsize=(10, 6))
sns.histplot(data=social_network_data, x='anomaly_score', hue='is_anomaly', element='step', palette='viridis')
plt.title('Distribution of Anomaly Scores')
plt.xlabel('Anomaly Score')
plt.ylabel('Count')
plt.show()

from sklearn.decomposition import PCA
pca = PCA(n_components=2)
X_pca = pca.fit_transform(X)

plt.figure(figsize=(10, 6))
sns.scatterplot(x=X_pca[:, 0], y=X_pca[:, 1], hue=social_network_data['is_anomaly'], palette='viridis', style=social_network_data['is_anomaly'], s=100)
plt.title('Anomaly Visualization with PCA')
plt.xlabel('Principal Component 1')
plt.ylabel('Principal Component 2')
plt.legend(title='Anomaly', labels=['Normal', 'Anomaly'])
plt.show()

# "Anomalies may not be as effectively highlighted by PCA,
# but they are effectively highlighted by the histogram plotted above."